images:
  - name: "taskmanager"
    source: "{{ ghcr_registry }}/cepha-manager:26.07.1"
    target: "taskmanager:latest"
  - name: "fluent-bit"
    source: "{{ ghcr_registry }}/cepha-fluent-bit:26.05.30"
    target: "fluent-bit:latest"
  - name: "busybox"
    source: "docker.io/library/busybox:latest"
    target: "busybox:latest"

compose:
  project_name: "{{ project_name }}-taskmanager"
  file: "docker-compose.taskmanager.yml"

flink:
  taskmanager_host: "{{ ansible_host }}"