# VM2: Kafka + Kafka-Producer
# Host: <KAFKA_IP>

services:
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      CLUSTER_ID: 4L6g3nShT-eMCtK--X86sw

      # Listeners - PLAINTEXT_HOST wird von externen Clients genutzt (andere VMs)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://<KAFKA_IP>:29092,PLAINTEXT_HOST://<KAFKA_IP>:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_MIN_ISR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    volumes:
      - /mnt/data/kafka:/var/lib/kafka/data
      - ./init-kafka-topics.sh:/init-kafka-topics.sh

    command: >
      bash -c "
      /etc/confluent/docker/run &
      echo 'Warte auf Kafka...' &&
      until kafka-broker-api-versions --bootstrap-server localhost:9092 > /dev/null 2>&1; do
        sleep 2;
      done &&
      bash /init-kafka-topics.sh && wait"

    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - cepha-network

networks:
  cepha-network:
    driver: bridge
