[SERVICE]
    Flush         2
    Daemon        Off
    Log_Level     info
    Parsers_File  /fluent-bit/etc/parsers.conf

[INPUT]
    Name              tail
    Path              /opt/flink/results/*/*/part-*
    Tag               detection.results
    Refresh_Interval  5
    Read_from_Head    true
    Skip_Long_Lines   On
    DB                /tmp/${FLUENT_BIT_DB_NAME}

[FILTER]
    Name          parser
    Match         detection.results
    Key_Name      log
    Parser        json
    Reserve_Data  On

[FILTER]
    Name          modify
    Match         detection.results
    Add           source    ${FLUENT_BIT_SOURCE}
    Add           host      ${HOSTNAME}
    Add           pipeline  covert-detection

[OUTPUT]
    Name              http
    Match             detection.results
    Host              ${OPENOBSERVE_HOST}
    Port              ${OPENOBSERVE_PORT}
    URI               /api/${OPENOBSERVE_ORG}/${OPENOBSERVE_STREAM}/_json
    Format            json
    Json_date_key     timestamp
    Json_date_format  iso8601
    HTTP_User         ${OPENOBSERVE_USER}
    HTTP_Passwd       ${OPENOBSERVE_PASSWORD}
    Compress          gzip